In [13]:
from sklearn.linear_model import Ridge
import numpy as np

LAMBDA = 1
LOG_SCALE = 8
SCALE = 1 << LOG_SCALE
PRIME_64 = 18446744072637906947
PRIME_128 = 340282366920938463463374607429104828419
PRIME_256 = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF98C00003
PRIME = PRIME_256

In [16]:
n_samples, n_features = 3, 3
rng = np.random.RandomState(0)
y = np.array([1.0, 2.0, 3.0])
X = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 10.0]])
# X = np.random.rand(n_samples, n_features)
# y = np.random.rand(n_samples)
dmin = np.min([np.min(X), np.min(y)])
dmax = np.max([np.max(X), np.max(y)])
print(dmin, dmax)
minmax = lambda x: ((x - dmin) / (dmax - dmin)) * 2 - 1
y = minmax(y)
X = minmax(X)
X, y

1.0 10.0


(array([[-1.        , -0.77777778, -0.55555556],
        [-0.33333333, -0.11111111,  0.11111111],
        [ 0.33333333,  0.55555556,  1.        ]]),
 array([-1.        , -0.77777778, -0.55555556]))

In [17]:
def array_to_str(arr, prefix):
    if len(arr.shape) == 1:
        return "\n".join([f"    {prefix}_{i}:\n        SecretInteger: \"{round(x * SCALE)}\"" for i, x in enumerate(arr)]) 
    else:
        return "\n".join([array_to_str(arr[i], f"{prefix}_{i}") for i in range(arr.shape[0])]) + "\n"

print(array_to_str(X, "A") + array_to_str(y, "b"))

    A_0_0:
        SecretInteger: "-256"
    A_0_1:
        SecretInteger: "-199"
    A_0_2:
        SecretInteger: "-142"
    A_1_0:
        SecretInteger: "-85"
    A_1_1:
        SecretInteger: "-28"
    A_1_2:
        SecretInteger: "28"
    A_2_0:
        SecretInteger: "85"
    A_2_1:
        SecretInteger: "142"
    A_2_2:
        SecretInteger: "256"
    b_0:
        SecretInteger: "-256"
    b_1:
        SecretInteger: "-199"
    b_2:
        SecretInteger: "-142"


In [18]:
# LINEAR REGRESSION:
clf = Ridge(alpha=0, fit_intercept=False)
clf.fit(X, y)
# print(X, y)
print("This is the input to the program:")
print("A:", (X * SCALE).astype(np.int64))
print("b:", (y * SCALE).astype(np.int64))
print("lambda: ", LAMBDA * SCALE**2)
print("EXPECTED OUTPUT: ", clf.coef_, clf.intercept_)

print("For the output, we print the results:")
w_0 = -9750037619520
w_1 = -6822441714528
w_2 = -29682598492800
b_0 = 7496337347136

w = np.array([w_0, w_1, w_2]) / b_0
print("w:", w)
print("z:", b_0)

This is the input to the program:
A: [[-256 -199 -142]
 [ -85  -28   28]
 [  85  142  256]]
b: [-256 -199 -142]
lambda:  65536
EXPECTED OUTPUT:  [ 3.33333333e+00 -3.00000000e+00 -2.09082751e-13] 0.0
For the output, we print the results:
w: [-1.30064019 -0.91010335 -3.95961349]
z: 7496337347136
