# 👋 Welcome to Nillion's Nada Numpy Linear Regression Closed Form Training example

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/NillionNetwork/nada-numpy/blob/main/examples/linear_regression/linear_regression.ipynb)

This notebook will get you familiar with linear regression closed-form training in `nada-numpy`, Nillion's data processing framework on top of the Nada dsl

We are really excited for developers to build with our SDK, if you have any questions please do reach out to us on:

[![Discord](https://img.shields.io/badge/Discord-nillionnetwork-%235865F2?logo=discord)](https://discord.gg/nillionnetwork)
[![GitHub Discussions](https://img.shields.io/badge/GitHub_Discussions-NillionNetwork-%23181717?logo=github)](https://github.com/orgs/NillionNetwork/discussions)

# 1. Set up environment

The boring part!

Installs all required dependencies and spins up a local devnet that will run Nada programs

In [1]:
%%capture
!pip install nada-numpy

In [2]:
import os
import time
import sys
import uuid

In [3]:
# Configure telemetry settings
enable_telemetry = True  #@param {type:"boolean"}
my_github_username = "your-github-username"  #@param {type:"string"}

In [4]:
# Install the nilup tool and then use that to install the Nillion SDK
!curl https://nilup.nilogy.xyz/install.sh | bash

# Update Path if ran in colab
if "google.colab" in sys.modules:
    os.environ["PATH"] += ":/root/.nilup/bin"
    os.environ["PATH"] += ":/root/.nilup/sdks/latest/"

# Set telemetry if opted in
if enable_telemetry:
    identifier = f"nada-numpy-linear-regression-cf-{str(uuid.uuid4())}-{my_github_username}"
    !echo 'yes' | nilup instrumentation enable --wallet {identifier}

# Install the lastest SDK and initialise it
!nilup init
!nilup install latest
!nilup use latest

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7810  100  7810    0     0  15569      0 --:--:-- --:--:-- --:--:-- 15557

nilup has been installed into /home/vscode/.nilup/bin.

$PATH is already up-to-date. You may begin using nilup now!

By providing your Ethereum wallet address, you consent to the collection of telemetry data by the Nillion Network.
That includes but is not limited to
- The version of the SDK you are using
- The OS you are using
- The Processor Architecture you are using
- The SDK binary that you are running and the subcommand
- The wallet address you provided
- The errors produced by the SDK
We collect this data to understand how the software is used, and to better assist you in case of issues.
While we will not collect any personal information, we still recommend using a new wallet address that cannot be linked to your identity by any third party.
For

In [5]:
# Spin up local Nillion devnet
os.system("nohup nillion-devnet &")

time.sleep(5)  # Wait for devnet

ℹ️ cluster id is 9e68173f-9c23-4acc-ba81-4f079b639964
ℹ️ using 256 bit prime
ℹ️ storing state in /tmp/.tmphGXd3q (190.84Gbs available)
🏃 starting nilchain node in: /tmp/.tmphGXd3q/nillion-chain
⛓  nilchain JSON RPC available at http://127.0.0.1:48102
⛓  nilchain REST API available at http://localhost:26650
⛓  nilchain gRPC available at localhost:26649
🏃 starting node 12D3KooWMvw1hEqm7EWSDEyqTb6pNetUVkepahKY6hixuAuMZfJS
⏳ waiting until bootnode is up...
🏃 starting node 12D3KooWAiwGZUwSUaT2bYVxGS8jmfMrfsanZYkHwH3uL7WJPsFq
🏃 starting node 12D3KooWM3hsAswc7ZT6VpwQ1TCZU4GCYY55nLhcsxCcfjuixW57
👛 funding nilchain keys
📝 nillion CLI configuration written to /home/vscode/.config/nillion/nillion-cli.yaml
🌄 environment file written to /home/vscode/.config/nillion/nillion-devnet.env


In [6]:
if 'google.colab' in sys.modules:
  # If ran in Colab, clone the nada-numpy repo and navigate to the correct directory
  if not os.path.exists("nada-numpy"):
    !git clone https://github.com/NillionNetwork/nada-numpy.git
  os.chdir("nada-numpy/examples/linear_regression")

# 2. Build Nada program

We will now build the Nada program specified under `src/linear_regression.py`

You will see that it uses both our `nada-dsl` and `nada-numpy`.

In [7]:
!nada build

Building program: determinant
Build complete!
Building program: gauss_jordan
Build complete!
Building program: matrix_inverse
Build complete!
Building program: linear_regression_256
Build complete!
Building program: modular_inverse
Build complete!
Building program: linear_regression
Build complete!


In [8]:
# You will see that the program was compiled in a .nada.bin file
!ls target | grep linear_regression

linear_regression.nada.bin
linear_regression_256.nada.bin


# 3. (optional) Test Nada program

This step is optional but we can now test whether our newly compiled program behaves as expected!

Under `tests/linear_regression.yaml`, you will see a test file with provided inputs and expected outputs. We will now test whether if we provide the program with those inputs, the program returns the expected outputs or not.

*Note for the nerds: nada testing runs programs on a simulator instead of a network. This means that you can test programs without having a local devnet running!!*

In [9]:
!nada test

Running test: gauss_jordan
Building ...
Running ...
gauss_jordan: PASS

Running test: modular_inverse
Building ...
Running ...
modular_inverse: PASS

Running test: determinant-3
Building ...
Running ...
determinant-3: PASS

Running test: determinant_1
Building ...
Running ...
determinant_1: PASS

Running test: linear_regression_256_1
Building ...
Running ...
linear_regression_256_1: PASS

Running test: linear_regression_1
Building ...
Running ...
linear_regression_1: PASS

Running test: linear_regression_2
Building ...
Running ...
linear_regression_2: PASS

Running test: linear_regression_256_2
Building ...
Running ...
linear_regression_256_2: PASS

Running test: linear_regression
Building ...
Running ...
linear_regression: PASS

Running test: determinant_2
Building ...
Running ...
determinant_2: PASS

Running test: matrix_inverse
Building ...
Running ...
matrix_inverse: PASS



# 4. Run Nada program

The time has come to take our Nada program for a spin!

You will see that `main.py` contains some python logic that wants to interface with our brand spanking new Nada program. It uses Nillion's Python SDK to store and run the program on a local devnet.

In [10]:
!python3 main.py

-----STORE PROGRAM
Getting quote for operation...
Submitting payment receipt 2 unil, tx hash 739B6965814F546C0BD863F11F46F6441A64579B6D4135D77DDA52085F77CE0D
Stored program. action_id: 3rgqxWd47e171EUwe4RXP9hm45tmoXfuF8fC52S7jcFoQTnU8wPiL7hqWzyV1muak6bEg7iWhudwg4t2pM9XnXcp/linear_regression_256
Stored program_id: 3rgqxWd47e171EUwe4RXP9hm45tmoXfuF8fC52S7jcFoQTnU8wPiL7hqWzyV1muak6bEg7iWhudwg4t2pM9XnXcp/linear_regression_256
-----STORE SECRETS
[[-256 -199 -142]
 [ -85  -28   28]
 [  85  142  256]]
[-256 -199 -142]
Getting quote for operation...
Quote cost is 866 unil
Submitting payment receipt 866 unil, tx hash CE43BFB06691648708025CF7E62045275DA167690199F0966DA4957A84473582
Getting quote for operation...
Quote cost is 290 unil
Submitting payment receipt 290 unil, tx hash C75D3FD188EE5892744BFED97F134124BD68308491DCD4D39669F6D8757D12FF
-----COMPUTE
Getting quote for operation...
Quote cost is 251 unil
Submitting payment receipt 251 unil, tx hash 2EB3F5EA7514E835ED8185C875C514AB05E0B3FA448

Excuse my French but voilà, we did it!!

To recap, in this example we:
- Set up and installed all necessary Nillion libraries and dependencies.
- Created and built a Nada program using Nillion's `nada-dsl` and the `nada-numpy` library.
- Tested the behaviour of the Nada program.
- Ran a Python script that ran a Nada program on a local devnet using Nillion's `py_nillion_client`.