In [55]:
from sklearn.linear_model import Ridge
import numpy as np

LAMBDA = 1
LOG_SCALE = 8
SCALE = 1 << LOG_SCALE
PRIME_64 = 18446744072637906947
PRIME_128 = 340282366920938463463374607429104828419
PRIME_256 = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF98C00003
PRIME = PRIME_64

In [68]:
n_samples, n_features = 3, 3
rng = np.random.RandomState(0)
y = np.array([1.0, 2.0, 3.0])
X = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 10.0]])
X = np.random.rand(n_samples, n_features)
y = np.random.rand(n_samples)
dmin = np.min([np.min(X), np.min(y)])
dmax = np.max([np.max(X), np.max(y)])
print(dmin, dmax)
minmax = lambda x: ((x - dmin) / (dmax - dmin)) * 2 - 1
y = minmax(y)
X = minmax(X)
X, y

0.03995762659205315 0.9179748658678125


(array([[-0.26078361,  0.14873977, -0.28964906],
        [-0.8364387 , -1.        , -0.42895583],
        [ 1.        , -0.55284953, -0.90683079]]),
 array([-0.3732993 ,  0.8969407 ,  0.80767223]))

In [69]:
def array_to_str(arr, prefix):
    if len(arr.shape) == 1:
        return "\n".join([f"    {prefix}_{i}:\n        SecretInteger: \"{round(x * SCALE)}\"" for i, x in enumerate(arr)]) 
    else:
        return "\n".join([array_to_str(arr[i], f"{prefix}_{i}") for i in range(arr.shape[0])]) + "\n"

print(array_to_str(X, "A") + array_to_str(y, "b"))

    A_0_0:
        SecretInteger: "-67"
    A_0_1:
        SecretInteger: "38"
    A_0_2:
        SecretInteger: "-74"
    A_1_0:
        SecretInteger: "-214"
    A_1_1:
        SecretInteger: "-256"
    A_1_2:
        SecretInteger: "-110"
    A_2_0:
        SecretInteger: "256"
    A_2_1:
        SecretInteger: "-142"
    A_2_2:
        SecretInteger: "-232"
    b_0:
        SecretInteger: "-96"
    b_1:
        SecretInteger: "230"
    b_2:
        SecretInteger: "207"


(array([ 3.33333333e+00, -3.00000000e+00, -2.09082751e-13]), 0.0)

In [71]:
# LINEAR REGRESSION:
clf = Ridge(alpha=0, fit_intercept=False)
clf.fit(X, y)
# print(X, y)
print("This is the input to the program:")
print("A:", (X * SCALE).astype(np.int64))
print("b:", (y * SCALE).astype(np.int64))
print("lambda: ", LAMBDA * SCALE**2)
print("EXPECTED OUTPUT: ", clf.coef_, clf.intercept_)

print("For the output, we print the results:")
w_0 = 59019958205040
w_1 = -222796296523080
w_2 = 50986170211584
b_0 = 168683052742416

w = np.array([w_0, w_1, w_2]) / b_0
print("w:", w)
print("z:", b_0)

This is the input to the program:
A: [[ -66   38  -74]
 [-214 -256 -109]
 [ 256 -141 -232]]
b: [-95 229 206]
lambda:  65536
EXPECTED OUTPUT:  [ 0.34955574 -1.31704549  0.29775291] 0.0
For the output, we print the results:
w: [ 0.34988671 -1.32079834  0.30226018]
z: 168683052742416


In [60]:
print("Testing:")
print(w.dot(np.array([-1.0, -0.77777778, -0.55555556])))
print(w.dot(np.array([-0.33333333, -0.11111111, 0.11111111])))
print(w.dot(np.array([0.33333333, 0.55555556, 1.0])))

Testing:
-0.9987005125979102
-0.7764562608919229
-0.5529564252936963


In [64]:
# LINEAR REGRESSION:
clf = Ridge(alpha=LAMBDA, fit_intercept=False)
clf.fit(X, y)
# print(X, y)
print("This is the input to the program:")
print("A:", (X * SCALE).astype(np.int64))
print("b:", (y * SCALE).astype(np.int64))
print("lambda: ", LAMBDA * SCALE**2)
print("EXPECTED OUTPUT: ", clf.coef_, clf.intercept_)
print("For the output, we print the results:")
w_prime_0 = 846133370465120
w_prime_1 = 273407217202352
w_prime_2 = -484368433094232
b_0 = 1619974004139584

w = np.array([w_prime_0, w_prime_1, w_prime_2]) / b_0
print("w:", w)
print("z:", b_0)

This is the input to the program:
A: [[-256 -199 -142]
 [ -85  -28   28]
 [  85  142  256]]
b: [-256 -199 -142]
lambda:  65536
EXPECTED OUTPUT:  [ 0.52216789  0.16926255 -0.30000705] 0.0
For the output, we print the results:
w: [ 0.52231293  0.1687726  -0.29899766]
z: 1619974004139584


In [65]:
print("Testing:")
print(w.dot(np.array([-1.0, -0.77777778, -0.55555556])))
print(w.dot(np.array([-0.33333333, -0.11111111, 0.11111111])))
print(w.dot(np.array([0.33333333, 0.55555556, 1.0])))

Testing:
-0.4874706944585707
-0.22607878070932946
-0.03113079549622838
