In [77]:
from sklearn.linear_model import Ridge
import numpy as np

LAMBDA = 1
LOG_SCALE = 8
SCALE = 1 << LOG_SCALE
PRIME_64 = 18446744072637906947
PRIME_128 = 340282366920938463463374607429104828419
PRIME_256 = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF98C00003
PRIME = PRIME_64

In [78]:
n_samples, n_features = 4,4
rng = np.random.RandomState(0)
y = np.array([1.0, 2.0, 3.0])
X = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 10.0]])
X = np.array([[-0.33756427, -0.59006742, -0.30637147, -0.51704649, -0.97658846],
       [-0.87220378, -0.76543508,  0.9466865 , -0.50484231, -0.92577715],
       [-0.20340417, -0.97362711,  0.48923287, -0.82431967,  0.02660715],
       [-0.23517022,  0.3633736 ,  0.57052432,  0.61224344,  0.25094258],
       [-0.20193703, -0.71220435,  0.29693346, -0.97735989,  0.46817842]])
y = np.array([-0.1819593 ,  0.72611257,  0.25631995, -0.16825547,  0.32932077])
X = np.random.rand(n_samples, n_features)
y = np.random.rand(n_samples)
dmin = np.min([np.min(X), np.min(y)])
dmax = np.max([np.max(X), np.max(y)])
print(dmin, dmax)
minmax = lambda x: ((x - dmin) / (dmax - dmin)) * 2 - 1
y = minmax(y)
X = minmax(X)
X, y

0.03490154602277595 0.9753153442457155


(array([[ 0.0693673 , -0.82325974,  0.84138942, -0.9801436 ],
        [ 0.48363076, -0.56129117, -0.49502836, -0.81665677],
        [ 0.95970803,  0.69876231,  0.45454649,  0.79127841],
        [ 0.25247625, -1.        ,  0.81315686,  0.02830828]]),
 array([ 0.67994624, -0.79241077,  1.        , -0.79255055]))

In [79]:
print("This is the input to the program:")
print("A:", (X * SCALE).astype(np.int64))
print("b:", (y * SCALE).astype(np.int64))
print("lambda: ", LAMBDA * SCALE**2)

This is the input to the program:
A: [[  17 -210  215 -250]
 [ 123 -143 -126 -209]
 [ 245  178  116  202]
 [  64 -256  208    7]]
b: [ 174 -202  256 -202]
lambda:  65536


In [80]:
def array_to_str(arr, prefix, scale=SCALE):
    if len(arr.shape) == 1:
        return "\n".join([f"    {prefix}_{i}:\n        SecretInteger: \"{round(x * scale)}\"" for i, x in enumerate(arr)]) 
    else:
        return "\n".join([array_to_str(arr[i], f"{prefix}_{i}", scale) for i in range(arr.shape[0])]) + "\n"

print(array_to_str(X, "A") + array_to_str(y, "b"))

    A_0_0:
        SecretInteger: "18"
    A_0_1:
        SecretInteger: "-211"
    A_0_2:
        SecretInteger: "215"
    A_0_3:
        SecretInteger: "-251"
    A_1_0:
        SecretInteger: "124"
    A_1_1:
        SecretInteger: "-144"
    A_1_2:
        SecretInteger: "-127"
    A_1_3:
        SecretInteger: "-209"
    A_2_0:
        SecretInteger: "246"
    A_2_1:
        SecretInteger: "179"
    A_2_2:
        SecretInteger: "116"
    A_2_3:
        SecretInteger: "203"
    A_3_0:
        SecretInteger: "65"
    A_3_1:
        SecretInteger: "-256"
    A_3_2:
        SecretInteger: "208"
    A_3_3:
        SecretInteger: "7"
    b_0:
        SecretInteger: "174"
    b_1:
        SecretInteger: "-203"
    b_2:
        SecretInteger: "256"
    b_3:
        SecretInteger: "-203"


In [81]:
print(array_to_str(np.identity(n_features), "my_output", scale=1))

    my_output_0_0:
        SecretInteger: "1"
    my_output_0_1:
        SecretInteger: "0"
    my_output_0_2:
        SecretInteger: "0"
    my_output_0_3:
        SecretInteger: "0"
    my_output_1_0:
        SecretInteger: "0"
    my_output_1_1:
        SecretInteger: "1"
    my_output_1_2:
        SecretInteger: "0"
    my_output_1_3:
        SecretInteger: "0"
    my_output_2_0:
        SecretInteger: "0"
    my_output_2_1:
        SecretInteger: "0"
    my_output_2_2:
        SecretInteger: "1"
    my_output_2_3:
        SecretInteger: "0"
    my_output_3_0:
        SecretInteger: "0"
    my_output_3_1:
        SecretInteger: "0"
    my_output_3_2:
        SecretInteger: "0"
    my_output_3_3:
        SecretInteger: "1"



In [82]:
dim = 8
triangular = np.tril(np.arange(1, dim * dim + 1, 1).reshape(dim,dim))

print(array_to_str(triangular, "A", scale=1))
np.tril(triangular).diagonal().prod()

    A_0_0:
        SecretInteger: "1"
    A_0_1:
        SecretInteger: "0"
    A_0_2:
        SecretInteger: "0"
    A_0_3:
        SecretInteger: "0"
    A_0_4:
        SecretInteger: "0"
    A_0_5:
        SecretInteger: "0"
    A_0_6:
        SecretInteger: "0"
    A_0_7:
        SecretInteger: "0"
    A_1_0:
        SecretInteger: "9"
    A_1_1:
        SecretInteger: "10"
    A_1_2:
        SecretInteger: "0"
    A_1_3:
        SecretInteger: "0"
    A_1_4:
        SecretInteger: "0"
    A_1_5:
        SecretInteger: "0"
    A_1_6:
        SecretInteger: "0"
    A_1_7:
        SecretInteger: "0"
    A_2_0:
        SecretInteger: "17"
    A_2_1:
        SecretInteger: "18"
    A_2_2:
        SecretInteger: "19"
    A_2_3:
        SecretInteger: "0"
    A_2_4:
        SecretInteger: "0"
    A_2_5:
        SecretInteger: "0"
    A_2_6:
        SecretInteger: "0"
    A_2_7:
        SecretInteger: "0"
    A_3_0:
        SecretInteger: "25"
    A_3_1:
        SecretInteger: "26"
    A_

31872332800

In [88]:
# LINEAR REGRESSION:
clf = Ridge(alpha=0, fit_intercept=False)
clf.fit(X, y)
# print(X, y)
print("This is the input to the program:")
print("A:", np.round(X * SCALE))
print("b:", np.round(y * SCALE))
print("lambda: ", LAMBDA * SCALE**2)
print("EXPECTED OUTPUT: ", clf.coef_, clf.intercept_)

print("For the output, we print the results:")
w_0 = -454699470140514134
w_1 = 764832256704590120
w_2 = -6737844777135621490
w_3 = -550732746459012770
b_0 = -4688989182386089280

w = np.array([w_0, w_1, w_2, w_3]) / b_0
print("w:", w)
print("z:", b_0)

This is the input to the program:
A: [[  18. -211.  215. -251.]
 [ 124. -144. -127. -209.]
 [ 246.  179.  116.  203.]
 [  65. -256.  208.    7.]]
b: [ 174. -203.  256. -203.]
lambda:  65536
EXPECTED OUTPUT:  [-0.01305333  1.83362525  1.32261374 -1.09939845] 0.0
For the output, we print the results:
w: [ 0.09697175 -0.1631124   1.43695038  0.11745234]
z: -4688989182386089280


In [89]:
clf.coef_ * b_0

array([ 6.12069426e+16, -8.59784896e+18, -6.20172150e+18,  5.15506745e+18])

In [87]:
print("Testing:")
print(w.dot(X[0]), y[0])
print(w.dot(X[1]), y[1])
print(w.dot(X[2]), y[2])

Testing:
1.2349252174236403 0.6799462350323353
-0.6687973653061642 -0.7924107667048601
0.7251860156081849 1.0


In [ ]:
# LINEAR REGRESSION:
clf = Ridge(alpha=LAMBDA, fit_intercept=False)
clf.fit(X, y)
# print(X, y)
print("This is the input to the program:")
print("A:", (X * SCALE).astype(np.int64))
print("b:", (y * SCALE).astype(np.int64))
print("lambda: ", LAMBDA * SCALE**2)
print("EXPECTED OUTPUT: ", clf.coef_, clf.intercept_)
print("For the output, we print the results:")
w_prime_0 = 846133370465120
w_prime_1 = 273407217202352
w_prime_2 = -484368433094232
b_0 = 1619974004139584

w = np.array([w_prime_0, w_prime_1, w_prime_2]) / b_0
print("w:", w)
print("z:", b_0)

This is the input to the program:
A: [[-256 -199 -142]
 [ -85  -28   28]
 [  85  142  256]]
b: [-256 -199 -142]
lambda:  65536
EXPECTED OUTPUT:  [ 0.52216789  0.16926255 -0.30000705] 0.0
For the output, we print the results:
w: [ 0.52231293  0.1687726  -0.29899766]
z: 1619974004139584


In [ ]:
print("Testing:")
print(w.dot(np.array([-1.0, -0.77777778, -0.55555556])))
print(w.dot(np.array([-0.33333333, -0.11111111, 0.11111111])))
print(w.dot(np.array([0.33333333, 0.55555556, 1.0])))

Testing:
-0.4874706944585707
-0.22607878070932946
-0.03113079549622838
