In [2]:
from sklearn.linear_model import Ridge
import numpy as np

LAMBDA = 1
LOG_SCALE = 8
SCALE = 1 << LOG_SCALE
PRIME_64 = 18446744072637906947
PRIME_128 = 340282366920938463463374607429104828419
PRIME_256 = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF98C00003
PRIME = PRIME_64



In [22]:
n_samples, n_features = 3, 3
rng = np.random.RandomState(0)
y = np.array([1.0, 2.0, 3.0])
#X = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 10.0]])
X = np.array([[1.0, 0, 0], [2, 0, 0], [3, 0, 0]])
dmin = np.min([np.min(X), np.min(y)])
dmax = np.max([np.max(X), np.max(y)])
print(dmin, dmax)
minmax = lambda x: ((x - dmin) / (dmax - dmin)) * 2 - 1
y = minmax(y)
X = minmax(X)
X , y

1.0 10.0


(array([[-1.        , -0.77777778, -0.55555556],
        [-0.33333333, -0.11111111,  0.11111111],
        [ 0.33333333,  0.55555556,  1.        ]]),
 array([-1.        , -0.77777778, -0.55555556]))

In [46]:

clf = Ridge(alpha=LAMBDA, fit_intercept=False)
clf.fit(X, y)
# print(X, y)
print("This is the input to the program:")
print("A:", (X * SCALE).astype(np.int64))
print("b:", (y * SCALE).astype(np.int64))
print("lambda: ", LAMBDA * SCALE**3)

This is the input to the program:
A: [[-256 -199 -142]
 [ -85  -28   28]
 [  85  142  256]]
b: [-256 -199 -142]
lambda:  16777216


In [48]:
clf.coef_, clf.intercept_

(array([ 0.52216789,  0.16926255, -0.30000705]), 0.0)

In [36]:
print("For the output, we print the results:")
w_0 = 1102041164640
w_1 = -993683999568
w_2 = 1868226984
b_0 = 330643400256

w = np.array([w_0, w_1, w_2]) / b_0
print("w:", w)
print("z:", b_0)

For the output, we print the results:
w: [ 3.3330203  -3.0053042   0.00565028]
z: 330643400256


In [37]:
print("Testing:")
print(w.dot(np.array([-1.        , -0.77777778, -0.55555556])))
print(w.dot(np.array([-0.33333333, -0.11111111,  0.11111111])))
print(w.dot(np.array([ 0.33333333,  0.55555556,  1.        ])))

Testing:
-0.9987005125979102
-0.7764562608919229
-0.5529564252936963


In [49]:
print("For the output, we print the results:")
w_prime_0 = 846133370465120
w_prime_1 = 273407217202352
w_prime_2 = -484368433094232
b_0 = 1619974004139584

w = np.array([w_prime_0, w_prime_1, w_prime_2]) / b_0
print("w:", w)
print("z:", b_0)

For the output, we print the results:
w: [ 0.52231293  0.1687726  -0.29899766]
z: 1619974004139584


In [42]:
print("Testing:")
print(w.dot(np.array([-1.        , -0.77777778, -0.55555556])))
print(w.dot(np.array([-0.33333333, -0.11111111,  0.11111111])))
print(w.dot(np.array([ 0.33333333,  0.55555556,  1.        ])))

Testing:
0.6702580423531501
0.025552991134645434
-0.6624580675219536


In [7]:
U = np.array(
    [[1.0, 2.0, 3.0], 
     [1, 5.0, 0], 
     [2, 0, 0]])

L = np.array(
    [[0, 0, 1], 
     [0, 1, 6.0], 
     [1, 8.0, 1]])

In [8]:
U = np.array(
    [[1, 0, 0], 
     [1, 4, 0], 
     [2, 2, 3]])

L = np.array(
    [[1, 2, 3], 
     [0, 1, 3], 
     [0, 0, 1]])

In [9]:
L.T

array([[1, 0, 0],
       [2, 1, 0],
       [3, 3, 1]])

In [10]:
np.linalg.det(L @ U)

12.000000000000021

In [11]:

import random

def create_random_lower_triangular_matrix(n: int):
    """
    Create a random lower triangular matrix with the specified dimensions.

    Args:
        n (int): The size of the matrix.
        party (Party): The party object representing the current party.
        prefix (str): A prefix string to be used for generating random values.

    Returns:
        np.ndarray: A NumPy array representing a random lower triangular matrix.

    """
    # return np.tril(create_random_array([n, n], party, prefix))
    return np.array(
            [
                [
                    (
                        random.randint(0, PRIME) 
                        if i > j
                        else 1 if i == j else 0
                    )
                    for j in range(n)
                ]
                for i in range(n)
            ]
        ).astype(np.float64)


In [12]:
def create_random_upper_triangular_matrix(n: int):
    """
    Create a random upper triangular matrix with the specified dimensions.

    Args:
        n (int): The size of the matrix.
        party (Party): The party object representing the current party.
        prefix (str): A prefix string to be used for generating random values.

    Returns:
        np.ndarray: A NumPy array representing a random upper triangular matrix.

    """
    # return np.triu(create_random_array([n, n], party, prefix))
    return np.array(
            [
                [random.randint(0, PRIME) if i <= j else 0 for j in range(n)]
                for i in range(n)
            ]
        ).astype(np.float64)

N = 4
U = create_random_upper_triangular_matrix(4)
U

detU = U.diagonal().prod()
U, L,  detU

(array([[7.27082270e+18, 3.54264876e+18, 1.59235856e+19, 4.26975154e+18],
        [0.00000000e+00, 1.76906902e+19, 7.23200089e+18, 1.41720129e+19],
        [0.00000000e+00, 0.00000000e+00, 5.58014233e+18, 1.71705784e+18],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.76838342e+19]]),
 array([[1, 2, 3],
        [0, 1, 3],
        [0, 0, 1]]),
 1.2692583881032402e+76)

In [13]:

L = create_random_lower_triangular_matrix(4)
L

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.54486336e+19, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.43389161e+18, 1.80643929e+19, 1.00000000e+00, 0.00000000e+00],
       [1.33920433e+19, 1.78993965e+19, 1.38412122e+19, 1.00000000e+00]])

In [14]:
U, L

(array([[7.27082270e+18, 3.54264876e+18, 1.59235856e+19, 4.26975154e+18],
        [0.00000000e+00, 1.76906902e+19, 7.23200089e+18, 1.41720129e+19],
        [0.00000000e+00, 0.00000000e+00, 5.58014233e+18, 1.71705784e+18],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.76838342e+19]]),
 array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.54486336e+19, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [6.43389161e+18, 1.80643929e+19, 1.00000000e+00, 0.00000000e+00],
        [1.33920433e+19, 1.78993965e+19, 1.38412122e+19, 1.00000000e+00]]))

In [15]:
np.linalg.slogdet(U), np.linalg.slogdet(L)

(SlogdetResult(sign=1.0, logabsdet=175.2348998510795),
 SlogdetResult(sign=1.0, logabsdet=0.0))

In [16]:
np.linalg.slogdet(L @ U), np.linalg.slogdet(U @ L)

(SlogdetResult(sign=1.0, logabsdet=268.89394044447823),
 SlogdetResult(sign=1.0, logabsdet=271.30248847104997))

In [17]:
np.round(np.linalg.det(L @ U)) == np.round(np.linalg.det(U @ L))

False

In [18]:
L@U == U@L

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
A_ = A * SCALE
LAMBDA_ = LAMBDA * SCALE**2

In [34]:
(A_.T @ A_ + np.identity(3).astype(int) * LAMBDA_) >> (LOG_SCALE * 2) == A.T @ A + LAMBDA * np.identity(3).astype(int)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [35]:
np.linalg.det(A)

-3.000000000000001

In [19]:
np.triu(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])